/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImportRouteImport } from './routes/import'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutinesIndexRouteImport } from './routes/routines/index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises/index'
import { Route as RoutinesRoutineIdRouteImport } from './routes/routines/$routineId'
import { Route as ExercisesExerciseIdRouteImport } from './routes/exercises/$exerciseId'

const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesIndexRoute = RoutinesIndexRouteImport.update({
  id: '/routines/',
  path: '/routines/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoutineIdRoute = RoutinesRoutineIdRouteImport.update({
  id: '/routines/$routineId',
  path: '/routines/$routineId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesExerciseIdRoute = ExercisesExerciseIdRouteImport.update({
  id: '/exercises/$exerciseId',
  path: '/exercises/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/import': typeof ImportRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/routines/$routineId': typeof RoutinesRoutineIdRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/routines/': typeof RoutinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/import': typeof ImportRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/routines/$routineId': typeof RoutinesRoutineIdRoute
  '/exercises': typeof ExercisesIndexRoute
  '/routines': typeof RoutinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/import': typeof ImportRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/routines/$routineId': typeof RoutinesRoutineIdRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/routines/': typeof RoutinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/import'
    | '/exercises/$exerciseId'
    | '/routines/$routineId'
    | '/exercises/'
    | '/routines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/import'
    | '/exercises/$exerciseId'
    | '/routines/$routineId'
    | '/exercises'
    | '/routines'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/import'
    | '/exercises/$exerciseId'
    | '/routines/$routineId'
    | '/exercises/'
    | '/routines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  ImportRoute: typeof ImportRoute
  ExercisesExerciseIdRoute: typeof ExercisesExerciseIdRoute
  RoutinesRoutineIdRoute: typeof RoutinesRoutineIdRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  RoutinesIndexRoute: typeof RoutinesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/': {
      id: '/routines/'
      path: '/routines'
      fullPath: '/routines/'
      preLoaderRoute: typeof RoutinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/$routineId': {
      id: '/routines/$routineId'
      path: '/routines/$routineId'
      fullPath: '/routines/$routineId'
      preLoaderRoute: typeof RoutinesRoutineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$exerciseId': {
      id: '/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof ExercisesExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  ImportRoute: ImportRoute,
  ExercisesExerciseIdRoute: ExercisesExerciseIdRoute,
  RoutinesRoutineIdRoute: RoutinesRoutineIdRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  RoutinesIndexRoute: RoutinesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
